name: Setup action
description: Setup build action
runs:
  using: "composite"
  steps:
    - uses: hustcer/setup-nu@main
      with:
        version: "*"

    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Setup depot tools
      uses: 2ndlab/actions/setup-depot-tools@main

    - name: Setup PATH and ENV
      shell: nu {0}
      run: |
        let main_count = (git rev-list --count main | into int)
        let diff_count = (git rev-list --count main..HEAD | into int)
        let hash = (git rev-parse --short HEAD)
        let build = $"($main_count + $diff_count)+($hash)"
        [
            $"BuildVersion=($build)"
            $"SkiaSharpName=libSkiaSharp-($env.SkiaSharpVersion)-($env.UCRTVersion)-($build)"
            $"HarfBuzzSharpName=libHarfBuzzSharp-($env.SkiaSharpVersion)-($env.UCRTVersion)-($build)"
            $"BuildDir=($env.GITHUB_WORKSPACE)/out/windows/x64/"
            $"PackageName=2ndLAB.SkiaSharp.Static.($env.SkiaSharpVersion)-($env.UCRTVersion).($build)"
        ] | str join (char newline) | save --append $env.GITHUB_ENV
